[features]
seeds = true
skip-lint = false
resolution = true

[programs.mainnet]
spl_404 = "tMBvM2ioL9UuKM3HZAPimrkf2WYRuRZGFqgvyg74wAr"

[provider]
cluster = "https://mainnet.helius-rpc.com/?api-key=f250da45-6c3b-491c-a1de-3e98c16b4b75"
wallet = "/Users/dannpl/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
