[features]
seeds = true
skip-lint = false
resolution = true

[programs.mainnet]
spl_404 = "tMBvM2ioL9UuKM3HZAPimrkf2WYRuRZGFqgvyg74wAr"

[provider]
cluster = "https://serene-few-tent.solana-mainnet.quiknode.pro/4ca22aff62d23b5e3b21ae38eab7f8a7f91c86d9/"
wallet = "/Users/dannpl/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
