[features]
seeds = false
skip-lint = false

[programs.devnet]
spl_404 = "7x6Jq7Yev6bxbRXcFPhagWReg472hD8B27hWRn4UKLYV"

[registry]
url = "devnet"

[provider]
cluster = "devnet"
wallet = "/Users/dannpl/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
