[features]
seeds = true
skip-lint = false
resolution = true

[programs.mainnet]
spl_404 = "tMBvM2ioL9UuKM3HZAPimrkf2WYRuRZGFqgvyg74wAr"

[provider]
cluster = "https://api.mainnet-beta.solana.com"
wallet = "/Users/dannpl/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
