[features]
seeds = false
skip-lint = false

[programs.localnet]
spl_404 = "M3Bw24wkaP3NzihBE8adrDk9UPfuLmWEEEbhiUXnfYS"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "devnet"
wallet = "/Users/dannpl/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
