[features]
seeds = false
skip-lint = false

[programs.devnet]
spl_404 = "t4o4cdvxFDEoZZzvDMnhQSJuRv97J1aFR7Sr6GxB3a1"

[registry]
url = "https://devnet.helius-rpc.com/?api-key=f250da45-6c3b-491c-a1de-3e98c16b4b75"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=f250da45-6c3b-491c-a1de-3e98c16b4b75"
wallet = "/Users/dannpl/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
