[features]
seeds = false
skip-lint = false

[programs.localnet]
spl_404 = "H74m4U3uNH9odM9Mn7UkdbMbfszLzShuqtgwqn8DRh77"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/dannpl/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
